# Generated by Django 4.0.1 on 2022-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armor',
            options={'verbose_name': 'Броня', 'verbose_name_plural': 'Броня'},
        ),
        migrations.AlterModelOptions(
            name='gem',
            options={'verbose_name': 'Самоцвет', 'verbose_name_plural': 'Самоцветы'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружие'},
        ),
        migrations.AddField(
            model_name='wowclass',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=63, verbose_name='Иконка'),
        ),
    ]
